#ddev-generated
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# Derived from the browsersync addition.
# This is to expose the vite dev port.
version: '3.6'
services:
  web:
    expose:
      # needed so the upstream works:
      - ${VITE_HTTP_PORT:-5173}
    environment:
      # Set the vite-enabled js project here:
      - VITE_PROJECT_DIR=${VITE_PROJECT_DIR:-frontend}
      # Expose the vite dev server's port (default 5173) here.
      # The odd port swap below is required so we do not need
      # to play with HMR settings due to different internal
      # and external ports. DDEV won't let us expose just HTTPS,
      # so a bit of trickery is required.
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,${VITE_HTTPS_PORT:-5174}:${VITE_HTTP_PORT:-5173}
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,${VITE_HTTP_PORT:-5173}:${VITE_HTTP_PORT:-5173}
